# version: "3.7"
version: "2.3"
services:
  dev_env:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile

    user: "ada"
    working_dir: /home/ada
    
    network_mode: host

    init: true
    privileged: true

    environment: 
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - UDEV=1
      # Fix audio in gazebo problems
      #- PULSE_SERVER=unix:/run/user/1000/pulse/native 
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspace

      # Forwards the local Docker socket to the container.
      - /var/run/docker.sock:/var/run/docker.sock

      # Enable GUI environments
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # Enable kernel modules (v4l2loopback)
      - /lib/modules:/lib/modules
      # Enable creating/reading inside docker new devices
      - /dev:/dev
    # devices: 
    #   - /dev/input:/dev/input
    #   - /dev/snd:/dev/snd
      
    cap_add:
      - SYS_PTRACE

    security_opt:
      - seccomp:unconfined

    # Overrides default command so things don't shut down after the process ends.
    # command: sleep infinity 
    stdin_open: true
    tty: true

    command: "/bin/bash" 